events {}

http {
    upstream master_nodes {
        
        server distributed-ai-master-9001:8000;
        server distributed-ai-master-9002:8000;
    }

    server {
        listen 80;

        # how long nginx waits for the client to send a request
        client_header_timeout 300s;
        client_body_timeout   300s;

        # how long nginx waits for the upstream (master) to respond
        proxy_read_timeout    300s;
        proxy_connect_timeout 10s;
        proxy_send_timeout    300s;

        # how long to keep client connections alive
        keepalive_timeout     300s;

        location / {
            proxy_pass http://master_nodes;
            proxy_http_version 1.1;
            proxy_set_header Connection "";
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_next_upstream error timeout http_502;
            proxy_next_upstream_timeout 5s;
        }
    }
}
